### PR TITLE
Remove define ID_AA64MMFR2_EL1 in AArch64Support.masm, because it is now present in VS2019 toolchain

### PR DESCRIPTION
**Pull request by mebersol**
Remove define for ID_AA64MMFR2_EL1

### CODE REVIEW

**Review by corthon — APPROVED** [review]
Do we have any justification for this? If so, can you add it in the commit notes? The behavior itself is pretty self-evident, but any reviewer in the future would want to know why it was there before and why it's no longer needed now.

**Review by spbrogan — APPROVED** [review]

**Review by spbrogan — COMMENTED** [review]
Should we wrap this in a VS2019 version check?

**Comment by mebersol** [comment]
> Should we wrap this in a VS2019 version check?
What would this look like?

**Comment by spbrogan** [comment]
I need to look up how to do it in the assembler. But here is an example for C code. 

https://github.com/microsoft/mu_basecore/blob/release/202102/MdePkg/Include/X64/ProcessorBind.h#L104

**Pull request merged**
