### PR TITLE
[SQUASH] Revert "ArmPkg: SmmVariablePei: Introduce variable read service in PEI"

### PR DESCRIPTION
**Pull request by kuqin12**
## Description

This reverts commit 852a5e5b512772d482f2ebcd43579d3de78fda1e, because the variable PEI module is upstreamed to MdeModulePkg in edk2.

For details on how to complete these options and their meaning refer to [CONTRIBUTING.md](https://github.com/microsoft/mu/blob/HEAD/CONTRIBUTING.md).

- [x] Impacts functionality?
- [ ] Impacts security?
- [x] Breaking change?
- [ ] Includes tests?
- [ ] Includes documentation?
- [ ] Backport to release branch?

## How This Was Tested

This was tested on QEMU SBSA platform.

## Integration Instructions

Replace the `  ArmPkg/Drivers/SmmVariablePei/SmmVariablePei.inf` with `MdeModulePkg/Universal/Variable/MmVariablePei/MmVariablePei.inf` in platform build tree.

### CODE REVIEW

**Review by os-d — APPROVED** [review]

**Comment by os-d** [comment]
@kuqin12 should this be backported to the release branch or was the CP only in dev?

**Comment by kuqin12** [comment]
> @kuqin12 should this be backported to the release branch or was the CP only in dev?

Yep, I will backport it to 2405 and 2311 release branches as well.

**Comment by os-d** [comment]
> > @kuqin12 should this be backported to the release branch or was the CP only in dev?
> 
> Yep, I will backport it to 2405 and 2311 release branches as well.

To backport to 2405 release, you just need to check the backport tick (or at this point you probably have to manually add the type:backport label). Unless it is a non-trivial cp to the release branch

**Comment by kuqin12** [comment]
> > > @kuqin12 should this be backported to the release branch or was the CP only in dev?
> > 
> > 
> > Yep, I will backport it to 2405 and 2311 release branches as well.
> 
> To backport to 2405 release, you just need to check the backport tick (or at this point you probably have to manually add the type:backport label). Unless it is a non-trivial cp to the release branch

Thanks. I added the label. Also, I think it is not worthy to backport to 2311 release as a breaking change. But I think we need to break it in 2405.

**Review by apop5 — APPROVED** [review]

**Pull request merged**
